### ISSUE TITLE
Create a script that will install NPM packages required by nonClinicalRPCs

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#125]
### Motivation
As it is now, development work in the **nonClinicalRPCs** repo requires that NPM package sets/dependencies are installed in multiple locations/directory. It would be convenient if we had a script that we could run from within the repo that would branch out and automatically install those dependencies.

### Tasks
* [x] Create script, which will install all `npm`-based package dependencies required by **nonClinicalRPCs**
* [x] Add script to `package.json` to make it runnable from `npm` (i.e. `npm run <<task name>>`)
* [x] Document the script existence in the project [wiki](https://github.com/vistadataproject/nonClinicalRPCs/wiki/Begin-with-Installation-:-First-Steps#npm-package-installation)
* [ ] Expanding scope, but possibly enhance the script to `git pull` all the repos that **nonClinicalRPCs** depend on.
