### ISSUE TITLE
Implement FILE RPCs with Issues/Blockers

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#155]
This issue is a collection point for all the RPCs for which blocker issues were discovered. For the most part, we're going to defer the implementation of these RPCs until later, but we still need to keep track of them...

### RPCs

- [ ] [F233 XUS DIVISION GET](http://vistadataproject.info/artifacts/vistaRPC%20documentation/XUS%20DIVISION%20GET)
    **External Routines**: CHKDIV^XUS1, NS^XUAF4
    **Issues**: Possible FILE WRITE in local **UPDIV**

- [ ] [F191 ORWUL FV4DG](http://vistadataproject.info/artifacts/vistaRPC%20documentation/ORWUL%20FV4DG)
    **External Routines**: ISQED^%ZTLOAD, FMADD^XLFDT, NOW^XLFDT
    **Issues**: Multiple FILE WRITES
    **Notes**: 
    > This RPC has some challenges associated with it. In Line 5 we first get the current time in HOROLOG format and assign it to UPDTIME.
    >  
    > UPDTIME=$H,
    > 
    > Then you go on and assign that value to the 101.43 file.
    > 
    > ^ORD(101.43,"AH","S."_DGNM)=UPDTIME
    > 
    > the problem is that "AH" and "S.+incomingArgument" passed through the VDM crossReference only returns an error message so far, and the index strings are undocumented in fileman and osehra.org site. I've only passed a handful of integers as arguments so for time sake I am leaving this one to take care for later.
    > 
    > Then we got a mean method here that gets invoked called FVBLD that rebuild an ORWSET entry line by line but that is an issue for another time....
    > . D FVBLD
    > 
    > Not only is this RPC probably mis-classified (should be a CHANGE instead of a READ, which has lower implementation priority), but there doesn't seem to be a way to set the required Fileman entries via VDM. We may have to push this one a lot farther down the stack.

- [ ] [F229 TIU TEMPLATE GETROOTS](http://vistadataproject.info/artifacts/vistaRPC%20documentation/TIU%20TEMPLATE%20GETROOTS)
    **External Routines**: ROOTIDX^TIUDDT
    **Issues**: Possible FILE WRITE
    **Notes**:
    > Potential File Write
