### ISSUE TITLE
Expand the Lexicon Search App to include lexical search for allergies 

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#241]
## Description
Create a user interface to allow lexical search for allergies. We've already implemented the RPC that allows us to perform a lexical search for allergies,  allergens, drug allergies and drug component allergies. (ORWDAL32 ALLERGY MATCH). We can build on the work done for the Problem Lexicon Search Application to create a user interface similar to the Problem lexical search. Note that this Issue is a child of #230.

## Requirements
* As a user, if I enter a term into an input and click a button, then I should be shown a categorized list of allergy matches against the VistA allergen database. These categories include:
    * VA Allergies
    * Drugs (Generic, Trade, Local)
    * Drug Ingredients
    * VA Drug Classes

## Task Breakdown
* [ ] Implement the back-end REST endpoint to perform the allergy lexical search, using the *ORWDAL32 ALLERGY MATCH* RPC emulation as a base. This would mirror the
implementation technique used for Problems, where we used *ORQQPL4 LEX* to perform the problems lexical search.
* [ ] Clone or adjust the existing Problem Lexicon front-end code to allows users to search for allergies
* [ ] Integrate the allergy search front-end with the new back-end RESTful endpoint.

## Notes
* The allergen list should be based on the allergy selection listing screen in CPRS
* The allergens returned by the *ORWDAL32 ALLERGY MATCH* RPC comes in the following format:
``` 
1^VA Allergies File^^^TOP^+
    ... VA Allergies ...
3^National Drug File - Generic Drug Name^^^TOP^+
    ... Generic names for drug allergies ...
4^National Drug file - Trade Name^^^TOP^+
    ... Trade names for drug allergies ...
5^Local Drug File^^^TOP^+
    ... Local drug listing allergies ...
7^Drug Ingredients File^^^TOP^+
    ... Drug ingredients allergies ...
8^VA Drug Class File^^^TOP^+
    ... Drug Classes ...
```

**Comment by mfuroyama** [comment]
Addressed in VAM and wiki
