### ISSUE TITLE
Expand the Lexicon Search App to include lexical search for allergy symptoms

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#242]
## Description
Create a user interface to allow lexical search for allergy symptoms. We've already implemented the RPC that allows us to perform a lexical search for allergy symptoms. (ORWDAL32 SYMPTOMS). We can build on the work done for the Problem Lexicon Search Application to create a user interface similar to the Problem lexical search. Note that this Issue is a child of #230 and is a peer of #241.

## Requirements
* As a user, if I enter a term into an input and click a button, then I should be shown a categorized list of allergy symptoms against the VistA allergy symptom database.

## Task Breakdown
* [ ] Implement the back-end REST endpoint to perform the allergy lexical search, using the *ORWDAL32 SYMPTOMS* RPC emulation as a base. This would mirror the implementation technique used for Problems, where we used *ORQQPL4 LEX* to perform the problems lexical search.
* [ ] Clone or adjust the existing Problem Lexicon front-end code to allows users to search for allergy symptoms
* [ ] Integrate the allergy search front-end with the new back-end RESTful endpoint.

## Notes
* The allergy symptom list should be based on the symptom selection listing screen in CPRS
* The allergens returned by the *ORWDAL32 ALLERGY MATCH* RPC comes in the following format:
``` 
{IEN}^{ALLERGY NAME}
```

**Comment by mfuroyama** [comment]
Addressed in VAM and wiki
