### ISSUE TITLE
Design MVDM Lexicon Service

### ISSUE THREAD

**Issue by mfuroyama** [vistadataproject/nonClinicalRPCs#294]
### Background
the Lexicon, "drug lookup", "allergin lookup", "vital by name lookup" (does that exist?), "problem narrative lookup" ... these are all "Lexicon -> Concept Id" things. It's just that VISTA let each domain build their own and has different lookup RPCs per domain.

In an MVDM-based "concept service", we'd have one set of lookup operations across all concepts and just map RPCs appropriately.

### Objectives
* [ ] Convert the VDM Lexicon and clincal meta-data objects into optimized MVDM objects. (e.g. ICD 10, CPT, Skin tests, Problems, Allergens, etc.)
* [ ] Load Optimized MVDM objects to MongoDB
* [ ] Implement an MVDM Lexicon Service interface that covers all concept/code lookup required by CPRS (Lookup, Modification, Cross-Referencing, etc.)
    * Design must include mechanism to account for meta data per VISTA in centralized cross-VA service
* [ ] Modify existing RPC emulation implementations to use the new MVDM Lexicon Service. Start with the poor performance outliers, which are mostly lexicon type RPCs
* [ ] Benchmark and compare native vs. passthru vs. VDM emulation vs. MVDM Lexicon Service emulation

This work is tied into the MVDM and MongoDB optimization work

**Comment by mfuroyama** [comment]
Moved this to wiki, will be addressed in VAM
